### ISSUE TITLE
Kibana needs to be moved to a Docker container

### ISSUE THREAD

**Issue by grantcurell** [grantcurell/rock#15]
Kibana should be migrated to a Docker container.

Requirements:
- Migrate any of Rock's existing functionality into the container.
- Must automatically talk to the cluster created in https://github.com/rocknsm/rock/issues/208
- Kibana should be controlled by a service file.

This is the snippet from the Docker compose file that currently ]starts Elasticsearch.

```
  kibana:
    image: "kibana:PPTAGPP"
    network_mode: host
    ports:
      - "5601:5601"
    restart: "always"
    environment:
      - "ELASTICSEARCH_URL=http://dockervm.local:9200"
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5601
      - xpack.security.enabled=false
```
