### ISSUE TITLE
Need to create service files for harbor and portainer

### ISSUE THREAD

**Issue by grantcurell** [grantcurell/rock#21]
Portainer and Harbor are currently missing service files. Service files need to be created and the appropriate enable variables included in a task. For example:

```
-  name: Enable and start broctl
   service:
     name: broctl
     enabled: "{{ enable_bro }}"
     state: "{{ 'started' if enable_bro else 'stopped' }}"
```
They also need to be included in the rock_start / rock_stop / rock_status scripts.
