### ISSUE TITLE
Firewall on at least Kibana and Docket are incorrect

### ISSUE THREAD

**Issue by grantcurell** [grantcurell/rock#44]
We're using the following code in the two:

```
- name: Configure firewalld
  firewalld:
    port: "{{ item[1].port }}"
    source: "{{ item[0] }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_nested:
    - "{{ rock_mgmt_nets }}"
    -
      - { port: "8443/tcp" }
```

rock_mgmt_nets should not be in each of them. We need to modify these to only allow the correct thing per role.
